### ISSUE TITLE
Receiving error on new game

### ISSUE THREAD

**Issue by Drizzt321** [perky/factorio-homeworld#2]
I'm getting the following error when I try and start a new game with Homeworld 0.5.2. I'm running Factorio 0.12.20, and no other mods enabled (although I have them installed, just disabled).

```
__homeworld__/control.lua:9: 
__homeworld__/homeworld_defines.lua:2: 
attempt to index global 'game' (a nil value)
```

**Comment by perky** [comment]
I haven't updated Homeworld since 0.12.0 so I don't think it supports 0.12.20. It needs a major overhaul and I'm waiting for 0.13 to be released before I do any extra work on it.

**Comment by Drizzt321** [comment]
Ah, this would be why. Ok, I understand. Hopefully 0.13 will be coming soon!
