### ISSUE TITLE
Sawmill unable to start

### ISSUE THREAD

**Issue by ddejong42** [perky/factorio-homeworld#3]
When you place a sawmill and load fuel in it, it will just sit there.  The problem seems to be that in sawmill.lua the Sawmill::can_operate function checks:

```
   and self.state.entity.energy > 0
```

It works for me if I change this to:

```
   and (self.state.entity.energy > 0 or not self.state.entity.get_inventory(1).is_empty())
```

**Comment by perky** [comment]
This is fixed in v1.0.1
