### ISSUE TITLE
_homeworld_/actors/terraformer.lua :28

### ISSUE THREAD

**Issue by ttyk** [perky/factorio-homeworld#5]
local wait_time = game.tick - self.state.last_step_tick

**self.state.last_step_tick** - is null and causing game to crash, when you placing terraformer on ground.

Probably its just a typo, i don't have time to investigate your code, but as a quick-fix i replaced it to
**self.last_step_tick**, as it assigned in meta function Terraformer:load() above.

**Comment by perky** [comment]
Fixed for next release. It should have been `self.state.last_step_tick` in all mentions.
